[project]
name = "hide"
version = "0.2.0"
description = "Copyright data embedding via steganography"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pillow>=10.4.0",
    "numpy>=2.1.2",
    "opencv-python>=4.10.0.84",
]

[project.scripts]
hide = "hide.cli:main"

[tool.pytest.ini_options]
pythonpath = [
  "src/"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
